version: '3'

vars:
  PREFIX_CMD: '{{if eq OS "windows"}}wsl{{else}}{{end}}'
  EXE_POSTFIX: '{{if eq OS "windows"}}.exe{{else}}{{end}}'
  MAELSTROM_VER: v0.2.3

tasks:
  prepare:
#    desc: Prepare project (maelstrom and build dependencies)
    deps: [install_maelstrom]
    cmds:
      - dotnet tool restore
      - dotnet paket restore

  echo:
    desc: Run the echo challenge
    deps: [ build ]
    cmds:
      - |
          {{.PREFIX_CMD}} ./maelstrom/maelstrom test -w echo --bin Echo/bin/Release/net6.0/echo{{.EXE_POSTFIX}} --node-count 1 --time-limit 10

  unique-ids:
    desc: Run the Unique ID Generation challenge
    deps: [ build ]
    cmds:
      - | 
          {{.PREFIX_CMD}} ./maelstrom/maelstrom test -w unique-ids --bin UniqueIDGeneration/bin/Release/net6.0/unique-ids{{.EXE_POSTFIX}}  --time-limit 30 --rate 1000 --node-count 3 --availability total --nemesis partition

  broadcast:
    desc: Run the Broadcast challenge
    deps: [ build ]
    cmds:
      - | 
          {{.PREFIX_CMD}} ./maelstrom/maelstrom test -w broadcast --bin Broadcast/bin/Release/net6.0/broadcast{{.EXE_POSTFIX}} --node-count 5 --time-limit 20 --rate 10 --nemesis partition

  broadcast:latency:
    desc: Run the Broadcast latency challenge
    deps: [ build ]
    cmds:
      - | 
          {{.PREFIX_CMD}} ./maelstrom/maelstrom test -w broadcast --bin Broadcast/bin/Release/net6.0/broadcast{{.EXE_POSTFIX}} --node-count 25 --time-limit 20 --rate 100 --latency 100

  broadcast:latency-partition:
    desc: Run the Broadcast latency challenge with partition split
    deps: [ build ]
    cmds:
      - | 
          {{.PREFIX_CMD}} ./maelstrom/maelstrom test -w broadcast --bin Broadcast/bin/Release/net6.0/broadcast{{.EXE_POSTFIX}} --node-count 25 --time-limit 20 --rate 100 --latency 100 --nemesis partition

  g-counter:
    desc: Run the Grow Only Counter challenge
    deps: [ build ]
    cmds:
      - | 
          {{.PREFIX_CMD}} ./maelstrom/maelstrom test -w g-counter --bin GrowOnlyCounter/bin/Release/net6.0/g-counter{{.EXE_POSTFIX}} --node-count 3 --time-limit 20 --rate 100 --nemesis partition

  build:
    cmds:
      - dotnet build -c Release

  view:
    desc: View results of the various runs
    cmds:
      - | 
        echo "IMPORTANT: If running on windows open http://localhost:8080 instead of what's printed below ..."
        echo
        {{.PREFIX_CMD}} ./maelstrom/maelstrom serve

  format:
    desc: Run format check
    cmds:
      - dotnet fantomas -r check Lib Echo Broadcast UniqueIDGeneration

  install_maelstrom:
    cmds:
      - |
        {{.PREFIX_CMD}} wget https://github.com/jepsen-io/maelstrom/releases/download/{{.MAELSTROM_VER}}/maelstrom.tar.bz2
        {{.PREFIX_CMD}} tar jxf maelstrom.tar.bz2
        {{.PREFIX_CMD}} rm maelstrom.tar.bz2
    status:
      - test -f ./maelstrom/maelstrom
