# For running exercises in windows using WSL for running maelstrom.
version: '3'

tasks:
  default:
    desc: Run all challenges
    deps:
      - broadcast
      - unique-ids
      - echo

  echo:
    desc: Run the echo challenge
    deps: [ build ]
    cmds:
      - wsl \~/maelstrom/maelstrom test -w echo --bin Echo/bin/Release/net6.0/echo.exe --node-count 1 --time-limit 10

  unique-ids:
    desc: Run the Unique ID Generation challenge
    deps: [ build ]
    cmds:
      - wsl \~/maelstrom/maelstrom test -w unique-ids --bin UniqueIDGeneration/bin/Release/net6.0/unique-ids.exe  --time-limit 30 --rate 1000 --node-count 3 --availability total --nemesis partition

  broadcast:
    desc: Run the Broadcast challenge
    deps: [ build ]
    cmds:
      - wsl \~/maelstrom/maelstrom test -w broadcast --bin Broadcast/bin/Release/net6.0/broadcast.exe --node-count 5 --time-limit 20 --rate 10 --nemesis partition

  build:
    cmds:
      - dotnet build -c Release

  view:
    desc: View results of the various runs
    cmds:
      - echo "Since we're running in WSL open http://localhost:8080 instead of what's printed below ..."
      - wsl \~/maelstrom/maelstrom serve

  format:
    desc: Run format check
    cmds:
      - dotnet fantomas -r check Lib Echo Broadcast UniqueIDGeneration
